export const CATEGORY_LABELS: Record<string, string> = {
  PHOTOGRAPHY: "Photography",
  VIDEOGRAPHY: "Videography",
  CATERING: "Catering",
  DECORATION: "Decoration & Florals",
  MUSIC_DJ: "Music & DJ",
  VENUE: "Venue",
  MC: "MC / Host",
  MAKEUP_HAIR: "Makeup & Hair",
  EVENT_PLANNING: "Event Planning",
  CAKE_DESSERTS: "Cake & Desserts",
  TRANSPORTATION: "Transportation",
  ASOEBI: "Asoebi & Fabric Sourcing",
  SOUVENIRS: "Souvenirs & Gifts",
  INVITATION_PRINT: "Invitation & Print Design",
  TENT_FURNITURE: "Tent, Chairs & Furniture",
  OTHER: "Other",
};

export const CATEGORY_ICONS: Record<string, string> = {
  PHOTOGRAPHY: "📸",
  VIDEOGRAPHY: "🎥",
  CATERING: "🍽️",
  DECORATION: "🌸",
  MUSIC_DJ: "🎵",
  VENUE: "🏛️",
  MC: "🎤",
  MAKEUP_HAIR: "💄",
  EVENT_PLANNING: "📋",
  CAKE_DESSERTS: "🎂",
  TRANSPORTATION: "🚗",
  ASOEBI: "🪡",
  SOUVENIRS: "🎁",
  INVITATION_PRINT: "✉️",
  TENT_FURNITURE: "⛺",
  OTHER: "✨",
};
